//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warpinator.Resources {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warpinator.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný a few seconds.
        /// </summary>
        internal static string a_few_seconds {
            get {
                return ResourceManager.GetString("a_few_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Any.
        /// </summary>
        internal static string any {
            get {
                return ResourceManager.GetString("any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Available devices.
        /// </summary>
        internal static string available_devices {
            get {
                return ResourceManager.GetString("available_devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Awaiting duplex.
        /// </summary>
        internal static string awaiting_duplex {
            get {
                return ResourceManager.GetString("awaiting_duplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Could not open web browser. Use this URL: {0}.
        /// </summary>
        internal static string cant_open_browser {
            get {
                return ResourceManager.GetString("cant_open_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Connected.
        /// </summary>
        internal static string connected {
            get {
                return ResourceManager.GetString("connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Connecting.
        /// </summary>
        internal static string connecting {
            get {
                return ResourceManager.GetString("connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Declined.
        /// </summary>
        internal static string declined {
            get {
                return ResourceManager.GetString("declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Selected directory does not exist, therefore this setting will not change.
        /// </summary>
        internal static string directory_doesnt_exist {
            get {
                return ResourceManager.GetString("directory_doesnt_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Disconnected.
        /// </summary>
        internal static string disconnected {
            get {
                return ResourceManager.GetString("disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Do you want to check for updates automatically?.
        /// </summary>
        internal static string do_you_want_to_check_for_updates {
            get {
                return ResourceManager.GetString("do_you_want_to_check_for_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Connection error.
        /// </summary>
        internal static string error_connection {
            get {
                return ResourceManager.GetString("error_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Could not decode certificate from {0}. Wrong group code?.
        /// </summary>
        internal static string error_groupcode {
            get {
                return ResourceManager.GetString("error_groupcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error while receiving: .
        /// </summary>
        internal static string error_receiving {
            get {
                return ResourceManager.GetString("error_receiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed.
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to open file for writing .
        /// </summary>
        internal static string failed_open_file {
            get {
                return ResourceManager.GetString("failed_open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to write to file {0}: {1}.
        /// </summary>
        internal static string failed_write_file {
            get {
                return ResourceManager.GetString("failed_write_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0} files.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný  (Files may be overwritten!).
        /// </summary>
        internal static string files_may_be_overwritten {
            get {
                return ResourceManager.GetString("files_may_be_overwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Finished.
        /// </summary>
        internal static string finished {
            get {
                return ResourceManager.GetString("finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Finished with errors.
        /// </summary>
        internal static string finished_errors {
            get {
                return ResourceManager.GetString("finished_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Incoming transfer from {0}.
        /// </summary>
        internal static string incoming_transfer {
            get {
                return ResourceManager.GetString("incoming_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Info.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Selected interface unavailable.
        /// </summary>
        internal static string interface_unavailable {
            get {
                return ResourceManager.GetString("interface_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný New version is available: {0} (current: {1}). Would you like to download it?.
        /// </summary>
        internal static string new_version_available {
            get {
                return ResourceManager.GetString("new_version_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No files were selected.
        /// </summary>
        internal static string no_files_selected {
            get {
                return ResourceManager.GetString("no_files_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Paused.
        /// </summary>
        internal static string paused {
            get {
                return ResourceManager.GetString("paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pick files to send.
        /// </summary>
        internal static string pick_files {
            get {
                return ResourceManager.GetString("pick_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pick folders to send.
        /// </summary>
        internal static string pick_folders {
            get {
                return ResourceManager.GetString("pick_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0} remaining.
        /// </summary>
        internal static string remaining {
            get {
                return ResourceManager.GetString("remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Send to.
        /// </summary>
        internal static string send_to {
            get {
                return ResourceManager.GetString("send_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sending failed with exception: .
        /// </summary>
        internal static string sending_failed {
            get {
                return ResourceManager.GetString("sending_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Service not running!.
        /// </summary>
        internal static string service_not_running {
            get {
                return ResourceManager.GetString("service_not_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Service is running.
        /// </summary>
        internal static string service_running {
            get {
                return ResourceManager.GetString("service_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Stopped.
        /// </summary>
        internal static string stopped {
            get {
                return ResourceManager.GetString("stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný WARN: Symlinks not supported.
        /// </summary>
        internal static string symlinks_not_supported {
            get {
                return ResourceManager.GetString("symlinks_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Transfer.
        /// </summary>
        internal static string transfer {
            get {
                return ResourceManager.GetString("transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Transferring.
        /// </summary>
        internal static string transferring {
            get {
                return ResourceManager.GetString("transferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný , unavailable.
        /// </summary>
        internal static string unavailable {
            get {
                return ResourceManager.GetString("unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unavailable interface: &quot;{0}&quot;.
        /// </summary>
        internal static string unavailable_interface {
            get {
                return ResourceManager.GetString("unavailable_interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Waiting for permission.
        /// </summary>
        internal static string waiting_for_permission {
            get {
                return ResourceManager.GetString("waiting_for_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
