//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warpinator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warpinator.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a few seconds.
        /// </summary>
        internal static string a_few_seconds {
            get {
                return ResourceManager.GetString("a_few_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device already connected.
        /// </summary>
        internal static string already_connected {
            get {
                return ResourceManager.GetString("already_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string any {
            get {
                return ResourceManager.GetString("any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available devices.
        /// </summary>
        internal static string available_devices {
            get {
                return ResourceManager.GetString("available_devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting duplex.
        /// </summary>
        internal static string awaiting_duplex {
            get {
                return ResourceManager.GetString("awaiting_duplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download directory does not exist and cannot be created. Please try picking a different one in the settings..
        /// </summary>
        internal static string cannot_create_dldir {
            get {
                return ResourceManager.GetString("cannot_create_dldir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open web browser. Use this URL: {0}.
        /// </summary>
        internal static string cant_open_browser {
            get {
                return ResourceManager.GetString("cant_open_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string connected {
            get {
                return ResourceManager.GetString("connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string connecting {
            get {
                return ResourceManager.GetString("connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        internal static string declined {
            get {
                return ResourceManager.GetString("declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected directory does not exist, therefore this setting will not change.
        /// </summary>
        internal static string directory_doesnt_exist {
            get {
                return ResourceManager.GetString("directory_doesnt_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string disconnected {
            get {
                return ResourceManager.GetString("disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to check for updates automatically?.
        /// </summary>
        internal static string do_you_want_to_check_for_updates {
            get {
                return ResourceManager.GetString("do_you_want_to_check_for_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string error_connection {
            get {
                return ResourceManager.GetString("error_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not decode certificate from {0}. Wrong group code?.
        /// </summary>
        internal static string error_groupcode {
            get {
                return ResourceManager.GetString("error_groupcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while receiving: .
        /// </summary>
        internal static string error_receiving {
            get {
                return ResourceManager.GetString("error_receiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open file for writing .
        /// </summary>
        internal static string failed_open_file {
            get {
                return ResourceManager.GetString("failed_open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start server: {0}.
        /// </summary>
        internal static string failed_to_start_server {
            get {
                return ResourceManager.GetString("failed_to_start_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write to file {0}: {1}.
        /// </summary>
        internal static string failed_write_file {
            get {
                return ResourceManager.GetString("failed_write_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Files may be overwritten!).
        /// </summary>
        internal static string files_may_be_overwritten {
            get {
                return ResourceManager.GetString("files_may_be_overwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string finished {
            get {
                return ResourceManager.GetString("finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished with errors.
        /// </summary>
        internal static string finished_errors {
            get {
                return ResourceManager.GetString("finished_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message from {0}.
        /// </summary>
        internal static string incoming_message {
            get {
                return ResourceManager.GetString("incoming_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming transfer from {0}.
        /// </summary>
        internal static string incoming_transfer {
            get {
                return ResourceManager.GetString("incoming_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected interface unavailable.
        /// </summary>
        internal static string interface_unavailable {
            get {
                return ResourceManager.GetString("interface_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified address is not in a valid format.
        /// </summary>
        internal static string invalid_address {
            get {
                return ResourceManager.GetString("invalid_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to device: {0}.
        /// </summary>
        internal static string manual_connect_error {
            get {
                return ResourceManager.GetString("manual_connect_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to connect to &quot;{0}&quot;?.
        /// </summary>
        internal static string manual_connect_to {
            get {
                return ResourceManager.GetString("manual_connect_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warpinator is not running on the given address, the running version does not yet support manual connection, or the device could not be reached on the network.
        /// </summary>
        internal static string manual_connect_unavailable {
            get {
                return ResourceManager.GetString("manual_connect_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warpinator on this device does not support manual connection.
        /// </summary>
        internal static string manual_connect_unsupported {
            get {
                return ResourceManager.GetString("manual_connect_unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual connection.
        /// </summary>
        internal static string manual_connection {
            get {
                return ResourceManager.GetString("manual_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual connection failed.
        /// </summary>
        internal static string manual_connection_failed {
            get {
                return ResourceManager.GetString("manual_connection_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available: {0} (current: {1}). Would you like to download it?.
        /// </summary>
        internal static string new_version_available {
            get {
                return ResourceManager.GetString("new_version_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files were selected.
        /// </summary>
        internal static string no_files_selected {
            get {
                return ResourceManager.GetString("no_files_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0} outside of group).
        /// </summary>
        internal static string outside_group {
            get {
                return ResourceManager.GetString("outside_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string paused {
            get {
                return ResourceManager.GetString("paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick files to send.
        /// </summary>
        internal static string pick_files {
            get {
                return ResourceManager.GetString("pick_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick folders to send.
        /// </summary>
        internal static string pick_folders {
            get {
                return ResourceManager.GetString("pick_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} remaining.
        /// </summary>
        internal static string remaining {
            get {
                return ResourceManager.GetString("remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send {0} file(s) to.
        /// </summary>
        internal static string send_to {
            get {
                return ResourceManager.GetString("send_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending failed with exception: .
        /// </summary>
        internal static string sending_failed {
            get {
                return ResourceManager.GetString("sending_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not running!.
        /// </summary>
        internal static string service_not_running {
            get {
                return ResourceManager.GetString("service_not_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is running.
        /// </summary>
        internal static string service_running {
            get {
                return ResourceManager.GetString("service_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string stopped {
            get {
                return ResourceManager.GetString("stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARN: Symlinks not supported.
        /// </summary>
        internal static string symlinks_not_supported {
            get {
                return ResourceManager.GetString("symlinks_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string transfer {
            get {
                return ResourceManager.GetString("transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring.
        /// </summary>
        internal static string transferring {
            get {
                return ResourceManager.GetString("transferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , unavailable.
        /// </summary>
        internal static string unavailable {
            get {
                return ResourceManager.GetString("unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable interface: &quot;{0}&quot;.
        /// </summary>
        internal static string unavailable_interface {
            get {
                return ResourceManager.GetString("unavailable_interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for permission.
        /// </summary>
        internal static string waiting_for_permission {
            get {
                return ResourceManager.GetString("waiting_for_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
